# Taken from https://github.com/tilt-dev/tilt-helm-demo/blob/d555fabbb1b3110582fb9d4f4e59c7d2ea337d37/values-dev.yaml.
image:
  repository: newrelic-infra-operator
  tag: latest

restartPolicy: Never

# Temporary extra values, required by newrelic-infra-operator chart.
cluster: testing
licenseKey: TEST

config:
  infraAgentInjection:
    policies:
      - {}


global:
  podLabels:
    "infra-operator.newrelic.com/disable-injection": "true"