# Taken from https://github.com/tilt-dev/tilt-helm-demo/blob/d555fabbb1b3110582fb9d4f4e59c7d2ea337d37/values-dev.yaml.
image:
  repository: newrelic-infra-operator
  tag: latest
  pullPolicy: Never

restartPolicy: Never

# Temporary extra values, required by newrelic-infra-operator chart.
cluster: testing
